# Generated by Django 5.2.1 on 2025-06-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasApp', '0002_alter_categoria_idcategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
