# Generated by Django 5.2.1 on 2025-06-18 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasApp', '0003_alter_categoria_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('idcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventasApp.categoria')),
            ],
        ),
    ]
