# Generated by Django 5.2.3 on 2025-06-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasApp', '0005_alter_producto_idcategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=80)),
                ('nombre', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
