# Generated by Django 5.2.1 on 2025-06-28 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasApp', '0006_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabeceraVenta',
            fields=[
                ('idventa', models.AutoField(primary_key=True, serialize=False)),
                ('idcliente', models.IntegerField()),
                ('fecha_venta', models.DateField()),
                ('estado', models.IntegerField()),
                ('total', models.FloatField()),
                ('nrodoc', models.CharField(max_length=12)),
                ('subtotal', models.FloatField()),
                ('igv', models.FloatField()),
            ],
            options={
                'verbose_name': 'CabeceraVenta',
                'verbose_name_plural': 'CabeceraVentas',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('idtipo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='ruc_dni',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idproducto', models.IntegerField()),
                ('precio', models.FloatField()),
                ('cantidad', models.FloatField()),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventasApp.cabeceraventa')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
            },
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeracion', models.CharField(max_length=15)),
                ('serie', models.CharField(max_length=3)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventasApp.tipo')),
            ],
            options={
                'verbose_name': 'Parámetro',
                'verbose_name_plural': 'Parámetros',
            },
        ),
        migrations.AddField(
            model_name='cabeceraventa',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventasApp.tipo'),
        ),
    ]
