# Generated by Django 5.2.1 on 2025-07-02 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasApp', '0007_cabeceraventa_tipo_cliente_ruc_dni_detalleventa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('idunidad', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='idunidad',
            field=models.ForeignKey(blank=True, db_column='idunidad', null=True, on_delete=django.db.models.deletion.CASCADE, to='ventasApp.unidad'),
        ),
    ]
