# Generated by Django 5.2.1 on 2025-07-02 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasApp', '0008_unidad_producto_idunidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabeceraventa',
            name='idcliente',
        ),
        migrations.AddField(
            model_name='cabeceraventa',
            name='cliente',
            field=models.ForeignKey(db_column='idcliente', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='ventasApp.cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cabeceraventa',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='idunidad',
            field=models.ForeignKey(db_column='idunidad', default=1, on_delete=django.db.models.deletion.CASCADE, to='ventasApp.unidad'),
            preserve_default=False,
        ),
    ]
